// Keep the complete SMS short and ASCII to avoid unnecessary SMS segments.
export const ROASTS = [
  'Clark. Angie. The couch has had enough of your asses. Go take a walk.',
  "It's 4 pm. Your shoes are starting to think they were adopted by furniture.",
  'Two adults. Four legs. Zero logged walks. Incredible use of resources.',
  'Your step count has the ambition of a decorative pillow. Outside. Both of you.',
  'The sidewalk called. It wants to know if you two are still alive.',
  'Congratulations on another elite performance in competitive sitting. Go walk.',
  'Your couch is not a life partner. You already have one. Take them outside.',
  'Clark and Angie: undefeated in finding reasons to remain horizontal.',
  'Breaking: local couple owns shoes, refuses to investigate their purpose.',
  'Go walk before the house starts listing you as included appliances.',
  "You don't need a fitness era. You need to put your damn shoes on.",
  'There are snacks on the other side of a walk. This is not a complicated quest.',
  "Your legs aren't just there to keep your pants from falling off. Use them.",
  'The bar is a lap around the block, you magnificent procrastinators.',
  "Clark. Angie. Go touch grass. Literally. I'm a walking app.",
  "It's 4 pm and your most impressive journey was probably to the fridge.",
  "Nobody said hike Everest. It's a sidewalk, you dramatic little houseplants.",
  'Even the Wi-Fi leaves the house more than you two. Go walk.',
  'Your matching hobby cannot be turning into couch sediment. Outside.',
  'A romantic stroll is just complaining together with forward momentum.',
  'Time to relocate the shit-talking outdoors. Take a lap together.',
  'You built a whole app to avoid forgetting a walk. And here we are.',
  'Imagine explaining to your shoes why a robot has to beg you to use them.',
  'This is your scheduled interruption of whatever sedentary bullshit this is.',
  "The neighborhood gossip isn't going to collect itself. Go patrol.",
  'Your daily walk is currently a very compelling work of fiction.',
  "The calendar has an empty square and frankly it's embarrassing for us all.",
  'Get outside before your knees start making dial-up modem noises.',
  'Somewhere a dog is walking without an app. Just putting that out there.',
  "You've scrolled a mile today. Now try doing that with your feet.",
  'Clark and Angie, your daily side quest is still sitting in the damn queue.',
  'There is a whole sky out there. Stunning development. Go look at it.',
  'Your couch sent a ticket to support. Subject: please get off me.',
  'Put on shoes. Open door. Move legs. I believe in your ability to follow this.',
  'Go be a cute walking couple instead of two tabs left open on a couch.',
  'The paper chain is not going to grow through positive thinking, nerds.',
  "Today's walk has more delays than an airport in a thunderstorm. Let's go.",
  'Fresh air is free, which fits your current exercise budget of zero effort.',
  "You're one lap away from being smug about it all evening. Go earn that.",
  'Walk first. Return to your regularly scheduled nonsense afterward.',
  'The outdoors has excellent resolution and no subscription fee. Try it.',
  'Your shoes have entered a committed relationship with the shoe rack.',
  'A walk together: cheaper than therapy, better than another episode.',
  'This household has too much sitting and not enough silly little strolling.',
  'I checked the logs. The logs said get your asses outside.',
  'Your daily movement cannot just be switching which leg is tucked under you.',
  "The walk won't do itself. I checked. That's not a feature yet.",
  'Clark. Angie. Your excuses have logged more miles than your feet.',
  'Go inspect a weird mailbox. Judge a lawn. Have a little walk, you gremlins.',
  'You two are dangerously close to qualifying as indoor decor.',
  "The couch isn't going anywhere. Which is apparently your shared strategy.",
  'A ten-minute walk would really interrupt this very busy day of not walking.',
  'Your future selves requested a walk. Your current selves need to get moving.',
  "Put the phones down. Hold hands. Or don't. Just move the damn feet.",
  'Some couples run marathons. We are currently negotiating a sidewalk.',
  'Another day, another chance to beat a Roomba at covering ground.',
  'You have a partner, shoes, and a door. This mission is fully funded.',
  'The only thing getting a workout is the list of excuses. Take a walk.',
  'This is a lovingly automated kick in both your pants. Outside time.',
  'Your shared streak is being held hostage by the comfiest seat in the house.',
  "Go make a memory that isn't the shape of your ass in a cushion.",
  'The sun has been up doing its job all day. Your turn, champions.',
  'You can discuss dinner while walking. Revolutionary multitasking bullshit.',
  "Your daily walk is marked 'concept of a plan.' Please ship the actual walk.",
  'Even this text traveled farther than you today. Shoes on, please.',
  'Four feet and not a single excuse worth hearing. Take each other outside.',
  'You are not charging cables. You do not have to stay plugged into the sofa.',
  'Good news: the block remains conveniently located around your house.',
  "Today's big adventure: opening the front door. Pace yourselves, legends.",
  'Consider this your performance review. Strong sitting. Weak walking.',
  'Please stop beta-testing what happens when humans become throw blankets.',
  "Walky believes in you. Walky's patience, however, has a 4 pm expiration.",
  'Your sneakers called a meeting. The agenda is your bullshit.',
  'All this excellent walking infrastructure and you two choose upholstery.',
  'One foot, then the other. Grab your favorite idiot and go.',
  'The grand expedition to Literally Anywhere Outside starts now.',
  "Your household's outdoor department has missed its entire daily quota.",
  'Go earn the right to dramatically announce that you exercised today.',
  'Two people who love each other should occasionally leave the same couch.',
  'This message was brought to you by your neglected legs. Go walk, dorks.',
];
export function roastForDay(date: string) {
  const day = Math.floor(Date.parse(date + 'T12:00:00Z') / 86400000);
  return `Walky: ${ROASTS[((day % ROASTS.length) + ROASTS.length) % ROASTS.length]} Reply STOP to opt out.`;
}
